import { sshReadDirScoped, sshReadFileScoped } from "../remote/remoteFs";
import { createProjectLensSnapshot, type ProjectLensSnapshot } from "./projectLens";
import { normalizeRemoteWorkspace, resolveRemoteWorkspacePath, type RemoteWorkspaceScope } from "./remoteWorkspace";

const KNOWN_FILES = [
  "package.json", "Cargo.toml", "pyproject.toml", "requirements.txt", "go.mod",
  "pom.xml", "build.gradle", "build.gradle.kts",
];
const CACHE_TTL_MS = 30_000;
const cache = new Map<string, { at: number; snapshot: ProjectLensSnapshot }>();

/** A remote Project Lens deliberately reads only one directory plus known
 * manifests/README files. Enabling it never turns into an unbounded crawl. */
export async function loadRemoteProjectLensSnapshot(
  scopeValue: RemoteWorkspaceScope,
  refresh = false,
): Promise<ProjectLensSnapshot> {
  const scope = normalizeRemoteWorkspace(scopeValue);
  if (!scope) throw new Error("Choose a valid remote workspace first");
  const key = `${scope.host}\n${scope.path}`;
  const cached = cache.get(key);
  if (!refresh && cached && Date.now() - cached.at < CACHE_TTL_MS) return cached.snapshot;

  const entries = await sshReadDirScoped(scope.host, scope.path, scope.path);
  const names = new Set(entries.filter((entry) => !entry.is_dir).map((entry) => entry.name));
  const readme = [...names].find((name) => /^readme(?:\.|$)/i.test(name));
  const wanted = [...KNOWN_FILES.filter((name) => names.has(name)), ...(readme ? [readme] : [])];
  const pairs = await Promise.all(wanted.map(async (name) => {
    const path = resolveRemoteWorkspacePath(name, scope.path);
    if (!path) return null;
    const content = await sshReadFileScoped(scope.host, scope.path, path).catch(() => null);
    return content == null ? null : [name, content] as const;
  }));
  const files = Object.fromEntries(pairs.filter((pair): pair is readonly [string, string] => pair !== null));
  const snapshot = createProjectLensSnapshot({
    root: scope.path,
    entries,
    files,
    git: { isRepository: false, branch: "", changedFiles: 0 },
  });
  snapshot.context = snapshot.context
    .replace("Generated locally by Husk from bounded project metadata.", `Generated by Husk from bounded metadata on SSH host ${scope.host}.`)
    .replace("Git: not a repository", "Git: not inspected over this remote connection");
  cache.set(key, { at: Date.now(), snapshot });
  return snapshot;
}
